language: php

php:
  - 7.4

os: linux

services:
  - mysql

before_install:
  - php

before_script:
  - chmod 777 -R storage
  - cp .env.example .env
  - mysql -e 'CREATE DATABASE livecommerce;'
  - php artisan key:generate
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - npm install
  - npm run dev
  - php artisan migrate --no-interaction


script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/assets/js/modules/*

cache:
  directories:
    - node_modules
    - vendor
